//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33, 150, 243")]
        public global::System.Drawing.Color PrimaryColor {
            get {
                return ((global::System.Drawing.Color)(this["PrimaryColor"]));
            }
            set {
                this["PrimaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151, 8, 204")]
        public global::System.Drawing.Color SecondaryColor {
            get {
                return ((global::System.Drawing.Color)(this["SecondaryColor"]));
            }
            set {
                this["SecondaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color InvertTextColor {
            get {
                return ((global::System.Drawing.Color)(this["InvertTextColor"]));
            }
            set {
                this["InvertTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 247, 255")]
        public global::System.Drawing.Color NormalHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["NormalHighlightColor"]));
            }
            set {
                this["NormalHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color NormalTextColor {
            get {
                return ((global::System.Drawing.Color)(this["NormalTextColor"]));
            }
            set {
                this["NormalTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color StrikedOutTextColor {
            get {
                return ((global::System.Drawing.Color)(this["StrikedOutTextColor"]));
            }
            set {
                this["StrikedOutTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color OverDueTextColor {
            get {
                return ((global::System.Drawing.Color)(this["OverDueTextColor"]));
            }
            set {
                this["OverDueTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color NavigationbarButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["NavigationbarButtonColor"]));
            }
            set {
                this["NavigationbarButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 255, 255, 255")]
        public global::System.Drawing.Color NavigationbarButtonHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["NavigationbarButtonHighlightColor"]));
            }
            set {
                this["NavigationbarButtonHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color PageBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PageBackgroundColor"]));
            }
            set {
                this["PageBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ControlColor_White {
            get {
                return ((global::System.Drawing.Color)(this["ControlColor_White"]));
            }
            set {
                this["ControlColor_White"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202, 202, 202")]
        public global::System.Drawing.Color ControlOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["ControlOutlineColor"]));
            }
            set {
                this["ControlOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 240, 201, 255")]
        public global::System.Drawing.Color ItembarHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["ItembarHighlightColor"]));
            }
            set {
                this["ItembarHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 230, 230")]
        public global::System.Drawing.Color ControlColor_LightGray {
            get {
                return ((global::System.Drawing.Color)(this["ControlColor_LightGray"]));
            }
            set {
                this["ControlColor_LightGray"] = value;
            }
        }
    }
}
